services:
  sender-crop:
    build: .
    container_name: sender-crop
    restart: unless-stopped
    volumes:
      - ./config:/app/config:rw
    env_file:
      - .env
    environment:
      - CAMERAS_CONFIG_PATH=/app/config/cameras.yaml
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
        reservations:
          cpus: "0.5"
          memory: 512M

